version: '3'

services: 
  # GrpcWeb proxy
  # Assumes running on macos
  # Assumes the backend is running at localhost:5001
  envoy:
    build:
      context: ./server/envoy
      dockerfile: Dockerfile
    image: ztl8702/yngdieng-api-frontend:dev
    network_mode: "host"
